# Generated by Django 5.2.3 on 2025-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='assigned_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1),
        ),
    ]
